### ISSUE TITLE
Need screenshots

### ISSUE THREAD

**Issue by techtonik** [lynix/vcp#4]
It is hard to see the awesomeness of added sugar coating without the picture of it.

**Comment by msx** [comment]
Propose yours!

**Comment by techtonik** [comment]
I am not a user yet, and to become one I need to see the benefits. catch 22.

**Comment by lynix** [comment]
What do you think of these?

![vcp-2](https://cloud.githubusercontent.com/assets/129653/6469666/b1c058fe-c1de-11e4-8176-71241af129e0.png)
![vcp-1](https://cloud.githubusercontent.com/assets/129653/6469671/b6216032-c1de-11e4-87b5-dc325fd30b47.png)

**Comment by msx** [comment]
:+1:

**Comment by techtonik** [comment]
Awesome.

**Comment by lynix** [comment]
Thanks :)

Closing the issue then - if you have further recommendations please comment.

**Comment by techtonik** [comment]
I can provide plenty. =) For example, cut them in half and use LICEcap for animated presentation,
